/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lostsys.lists.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TaskItemComment service. Represents a row in the &quot;Lostsys_TaskItemComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lostsys.lists.model.impl.TaskItemCommentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lostsys.lists.model.impl.TaskItemCommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskItemComment
 * @see com.lostsys.lists.model.impl.TaskItemCommentImpl
 * @see com.lostsys.lists.model.impl.TaskItemCommentModelImpl
 * @generated
 */
public interface TaskItemCommentModel extends BaseModel<TaskItemComment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task item comment model instance should use the {@link TaskItemComment} interface instead.
	 */

	/**
	 * Returns the primary key of this task item comment.
	 *
	 * @return the primary key of this task item comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task item comment.
	 *
	 * @param primaryKey the primary key of this task item comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this task item comment.
	 *
	 * @return the ID of this task item comment
	 */
	public long getId();

	/**
	 * Sets the ID of this task item comment.
	 *
	 * @param id the ID of this task item comment
	 */
	public void setId(long id);

	/**
	 * Returns the item of this task item comment.
	 *
	 * @return the item of this task item comment
	 */
	public long getItem();

	/**
	 * Sets the item of this task item comment.
	 *
	 * @param item the item of this task item comment
	 */
	public void setItem(long item);

	/**
	 * Returns the userid of this task item comment.
	 *
	 * @return the userid of this task item comment
	 */
	public long getUserid();

	/**
	 * Sets the userid of this task item comment.
	 *
	 * @param userid the userid of this task item comment
	 */
	public void setUserid(long userid);

	/**
	 * Returns the description of this task item comment.
	 *
	 * @return the description of this task item comment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task item comment.
	 *
	 * @param description the description of this task item comment
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskItemComment taskItemComment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskItemComment> toCacheModel();

	@Override
	public TaskItemComment toEscapedModel();

	@Override
	public TaskItemComment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}