/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lostsys.lists.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TaskList service. Represents a row in the &quot;Lostsys_TaskList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lostsys.lists.model.impl.TaskListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lostsys.lists.model.impl.TaskListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskList
 * @see com.lostsys.lists.model.impl.TaskListImpl
 * @see com.lostsys.lists.model.impl.TaskListModelImpl
 * @generated
 */
public interface TaskListModel extends BaseModel<TaskList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task list model instance should use the {@link TaskList} interface instead.
	 */

	/**
	 * Returns the primary key of this task list.
	 *
	 * @return the primary key of this task list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task list.
	 *
	 * @param primaryKey the primary key of this task list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this task list.
	 *
	 * @return the ID of this task list
	 */
	public long getId();

	/**
	 * Sets the ID of this task list.
	 *
	 * @param id the ID of this task list
	 */
	public void setId(long id);

	/**
	 * Returns the portlet of this task list.
	 *
	 * @return the portlet of this task list
	 */
	@AutoEscape
	public String getPortlet();

	/**
	 * Sets the portlet of this task list.
	 *
	 * @param portlet the portlet of this task list
	 */
	public void setPortlet(String portlet);

	/**
	 * Returns the description of this task list.
	 *
	 * @return the description of this task list
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task list.
	 *
	 * @param description the description of this task list
	 */
	public void setDescription(String description);

	/**
	 * Returns the weight of this task list.
	 *
	 * @return the weight of this task list
	 */
	public int getWeight();

	/**
	 * Sets the weight of this task list.
	 *
	 * @param weight the weight of this task list
	 */
	public void setWeight(int weight);

	/**
	 * Returns the ratings of this task list.
	 *
	 * @return the ratings of this task list
	 */
	public int getRatings();

	/**
	 * Sets the ratings of this task list.
	 *
	 * @param ratings the ratings of this task list
	 */
	public void setRatings(int ratings);

	/**
	 * Returns the comments of this task list.
	 *
	 * @return the comments of this task list
	 */
	public int getComments();

	/**
	 * Sets the comments of this task list.
	 *
	 * @param comments the comments of this task list
	 */
	public void setComments(int comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskList taskList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskList> toCacheModel();

	@Override
	public TaskList toEscapedModel();

	@Override
	public TaskList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}