/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lostsys.lists.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TaskItem service. Represents a row in the &quot;Lostsys_TaskItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lostsys.lists.model.impl.TaskItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lostsys.lists.model.impl.TaskItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskItem
 * @see com.lostsys.lists.model.impl.TaskItemImpl
 * @see com.lostsys.lists.model.impl.TaskItemModelImpl
 * @generated
 */
public interface TaskItemModel extends BaseModel<TaskItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task item model instance should use the {@link TaskItem} interface instead.
	 */

	/**
	 * Returns the primary key of this task item.
	 *
	 * @return the primary key of this task item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task item.
	 *
	 * @param primaryKey the primary key of this task item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this task item.
	 *
	 * @return the ID of this task item
	 */
	public long getId();

	/**
	 * Sets the ID of this task item.
	 *
	 * @param id the ID of this task item
	 */
	public void setId(long id);

	/**
	 * Returns the list of this task item.
	 *
	 * @return the list of this task item
	 */
	public long getList();

	/**
	 * Sets the list of this task item.
	 *
	 * @param list the list of this task item
	 */
	public void setList(long list);

	/**
	 * Returns the label of this task item.
	 *
	 * @return the label of this task item
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this task item.
	 *
	 * @param label the label of this task item
	 */
	public void setLabel(String label);

	/**
	 * Returns the weight of this task item.
	 *
	 * @return the weight of this task item
	 */
	public int getWeight();

	/**
	 * Sets the weight of this task item.
	 *
	 * @param weight the weight of this task item
	 */
	public void setWeight(int weight);

	/**
	 * Returns the status of this task item.
	 *
	 * @return the status of this task item
	 */
	public int getStatus();

	/**
	 * Sets the status of this task item.
	 *
	 * @param status the status of this task item
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this task item.
	 *
	 * @return the description of this task item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task item.
	 *
	 * @param description the description of this task item
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskItem taskItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskItem> toCacheModel();

	@Override
	public TaskItem toEscapedModel();

	@Override
	public TaskItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}